apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jey-app
spec:
  secretName: jey-app
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: jey.app
  dnsNames:
    - jey.app
    - www.jey.app